ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5/Controllers/AuthController.cs
using ShoppingCart_ASP.NET_MVC5.Dao;
using ShoppingCart_ASP.NET_MVC5.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;


namespace ShoppingCart_ASP.NET_MVC5.Controllers
{
    

    public class AuthController : Controller
    {
       
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (username == null)
                return View();

            Customer customer = CustomerDetails.GetCustomer(username);
            if (customer == null)
            {
                ViewData["warning1"] = "Wrong Username, Please try again";
                return View();
            }

            if(customer.username.Equals(username))
            {
                if (customer.password != CalculateMD5Hash(password).ToLower())
                {
                    ViewData["warning"] = "Wrong password, Please try again";
                    return View();
                }
            }
            else
            {
                ViewData["warning"] = "Invalid username";
                return View();
            }

            HttpCookie cookie = new HttpCookie("customer_id");
            HttpCookie firstname = new HttpCookie("firstname");
            HttpCookie Count = new HttpCookie("Count");
            Count.Value = "0";
            cookie.Value = customer.customer_id.ToString();
            firstname.Value = customer.firstname;
            HttpContext.Response.Cookies.Add(cookie);
            HttpContext.Response.Cookies.Add(Count);
            HttpContext.Response.Cookies.Add(firstname);
            return RedirectToAction("../Home/Home");
        }

        //Logout
        public ActionResult Logout(string sessionId, string username)
        {
            SessionManagement.RemoveSession(sessionId);
            return View("Login");
        }


        public string CalculateMD5Hash(string input)

        {
            MD5 md5 = MD5.Create();

            byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(input);
            byte[] hash = md5.ComputeHash(inputBytes);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < hash.Length; i++)
            {
                sb.Append(hash[i].ToString("X2"));
            }
            return sb.ToString();
        }
    }
}

ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5/Controllers/PurchaseController.cs
using ShoppingCart_ASP.NET_MVC5.Dao;
using ShoppingCart_ASP.NET_MVC5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.Data.SqlClient;

namespace ShoppingCart_ASP.NET_MVC5.Controllers
{
    [SessionExpire]
    public class PurchaseController : Controller
    {
        public ActionResult Purchase(string customer_id)
        {
            List<AllItemList> returnListofitems = PurchaseHistory.allhistory(customer_id);
            ViewBag.Products = returnListofitems;
            return View();
        }

       
        public ActionResult ViewCart()
        {
            HttpCookieCollection cookies = Request.Cookies;
            string[] arr = cookies.AllKeys;
            List<Cart> pro = new List<Cart>();
            foreach (var i in arr)
            {
                if (i.Any(Char.IsDigit))
                {
                    using (SqlConnection conn = new SqlConnection("Server=.; Database=ShoppingCartT4; Integrated Security=true"))
                    {
                        conn.Open();
                        string sql = @"select * from Product where pro_id = '" + i + "'";
                        SqlCommand cmd = new SqlCommand(sql, conn);
                        SqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            Cart p = new Cart()
                            {
                                pro_id = (int)reader["pro_id"],
                                pro_name = (string)reader["pro_name"],
                                pro_desc = (string)reader["pro_desc"],
                                pro_price = (int)reader["pro_price"],
                                pro_image = (string)reader["pro_image"],
                                count = int.Parse(Request.Cookies[i].Value)
                            };
                            pro.Add(p);
                        }
                    }
                }
            }
            ViewBag.customer = int.Parse(Request.Cookies["customer_id"].Value);
            ViewBag.firstname = Request.Cookies["firstname"].Value;
            ViewBag.Count = int.Parse(Request.Cookies["Count"].Value);
            ViewBag.cart = pro;
            return View();

        }

        public ActionResult Checkout()
        {
            HttpCookieCollection itemcookies = Request.Cookies;
            HttpCookie cuscookie = Request.Cookies["customer_id"];
            int customer = int.Parse(cuscookie.Value);
            string[] arr = itemcookies.AllKeys;

            Dictionary<string, string> kV = new Dictionary<string, string>();
            List<Product> pro = new List<Product>();
            foreach (var i in arr)
            {
                if (i.Length <= 3)
                {
                    for (int j = 0; j < int.Parse(Request.Cookies[i].Value); j++)
                    {
                        string guid = System.Guid.NewGuid().ToString();
                        using (SqlConnection conn = new SqlConnection("Server=.; Database=ShoppingCartT4; Integrated Security=true"))
                        {
                            conn.Open();
                            string sql = @"INSERT INTO Purchaseitem (customer_id,pro_id,activation_code,purchase_time) " +
                                "values (" + customer + "," + i + ",'" + guid + "','" + DateTime.Now.ToString("yyyy/MM/dd") + "');";
                            SqlCommand cmd = new SqlCommand(sql, conn);
                            SqlDataReader reader = cmd.ExecuteReader();
                            while (reader.Read())
                            {
                                Product p = new Product()
                                {
                                    pro_id = (int)reader["pro_id"],
                                    pro_name = (string)reader["pro_name"],
                                    pro_desc = (string)reader["pro_desc"],
                                    pro_price = (int)reader["pro_price"],
                                    pro_image = (string)reader["pro_image"]
                                };
                                pro.Add(p);
                            }
                        }
                    }
                }
            }
            foreach (string key in HttpContext.Request.Cookies.AllKeys)
            {
                if (key != "customer_id" && key != "firstname")
                {
                    HttpCookie c = HttpContext.Request.Cookies[key];

                    c.Expires = DateTime.Now.AddMonths(-1);
                    HttpContext.Response.AppendCookie(c);
                }
                HttpCookie Count = new HttpCookie("Count");
                Count.Value = "0";
                HttpContext.Response.Cookies.Add(Count);
            }

            return RedirectToAction("MyPurchases");
        }

        public ActionResult MyPurchases()
        {
            string customer_id = Request.Cookies["customer_id"].Value;
            List<PurchaseItems> allitems = new List<PurchaseItems>();
            using (SqlConnection conn = new SqlConnection("Server=.; Database=ShoppingCartT4; Integrated Security=true; MultipleActiveResultSets=True"))
            {
                conn.Open();
                string sql = @"select purchase_time, i.pro_id, pro_name, pro_desc, pro_image, count(i.pro_id) as count from Purchaseitem i join Product p on i.pro_id = p.pro_id where customer_id ='" + customer_id + "' group by i.pro_id, purchase_time, pro_name, pro_desc, pro_image";
                SqlCommand cmd = new SqlCommand(sql, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    PurchaseItems singleitem = new PurchaseItems();
                    singleitem.purchase_time = (DateTime)reader["purchase_time"];
                    singleitem.pro_id = (int)reader["pro_id"];
                    singleitem.pro_desc = (string)reader["pro_desc"];
                    singleitem.pro_image = (string)reader["pro_image"];
                    singleitem.pro_name = (string)reader["pro_name"];
                    singleitem.count = (int)reader["count"];
                    List<string> arr = new List<string>();

                    using (SqlConnection conn1 = new SqlConnection("Server=.; Database=ShoppingCartT4; Integrated Security=true; MultipleActiveResultSets=True"))
                    {
                        conn1.Open();

                        string sql1 = @"select activation_code from Purchaseitem where purchase_time='" + singleitem.purchase_time.ToString("yyyy-MM-dd") + "' and pro_id = '" + singleitem.pro_id + "' and customer_id='" +customer_id+"'";
                        SqlCommand cmd1 = new SqlCommand(sql1, conn);
                        SqlDataReader reader1 = cmd1.ExecuteReader();

                        while (reader1.Read())
                        {
                            arr.Add((string)reader1["activation_code"]);
                        }

                    }
                    singleitem.activation_code = arr;
                    allitems.Add(singleitem);
                }

            }
            ViewBag.purchases = allitems;
            ViewBag.Count = int.Parse(Request.Cookies["Count"].Value);
            ViewBag.firstname = Request.Cookies["firstname"].Value;
            return View();
        }


    }
}

ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5/Views/Purchase/MyPurchases.cshtml
@model ShoppingCart_ASP.NET_MVC5.Models.PurchaseItems
@using ShoppingCart_ASP.NET_MVC5.Models

<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

        .row.display-flex > [class*='col-'] {
            display: flex;
            flex-direction: column;
        }
</style>
<div style="width:100%;background-color:white;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12" style="text-align:right;">
                <i class="glyphicon glyphicon-user"></i> @ViewBag.firstname &nbsp;&nbsp;
                <i class="glyphicon glyphicon-eye-open"></i>  @Html.ActionLink("Home", "Home", "Home", null, null) &nbsp;&nbsp;
                <i class="glyphicon glyphicon-log-out"></i>@Html.ActionLink("Logout", "Logout", "Auth", null, null)

            </div>
        </div>
        <div class="row" style="padding:10px;">
            <div class="col-sm-3">
                <span style="font-family:Century Gothic;font-size:23px;">Just Cart</span>
            </div>
            <form action="/Search/Partial" name="Form"   method="post" onsubmit="return validate()">
                <div class="col-sm-5" style="text-align:right;">
                    <div class="row display-flex">
                        <input type="text" class="form-control" id="search" name="search" placeholder="Search.." style="max-width:100%" />
                    </div>

                </div>
                <div class="col-sm-1">
                    <span class="input-group-btn">
                        <button class="btn btn-search" type="submit" style="border-radius"><i class="glyphicon glyphicon-search"></i>&nbsp;&nbsp; Search</button>
                    </span>
                </div>
            </form>
            <div class="col-sm-3" style="text-align:right;">
                <form action="/Purchase/ViewCart" method="get">
                    <button style="border-color:transparent;border-radius:30px;padding-top:5px;">
                        <span class="glyphicon glyphicon-shopping-cart">
                        </span>
                        <span class="items">
                            <p id="count" value="" class="badge">
                                @ViewBag.Count
                            </p>
                        </span>
                    </button>

                </form>

            </div>
        </div>
    </div>
</div>   
@{
<div class="container-fluid" style="margin-top:10px">
    <div class="row display-flex">

        @foreach (var pur in ViewBag.purchases)
        {
        <div class="col-sm-4">
            <table class="table table-bordered" style="border-color:transparent; box-shadow: 0 1px 9px 0 rgba(0, 0, 0, 0.1), 0 1px 10px 0 rgba(0, 0, 0, 0.19);border-top-left-radius:30px;border-top-right-radius:30px;">
                <tr style="text-align:center">

                    <td colspan="2" style="border-color:transparent;">
                        <img src="~/images/@pur.pro_image" style="width:40%" /><br />
                         <span style="color:#337ab7">@pur.pro_name<br />
                         <span style="color:indianred">Description : </span>@pur.pro_desc<br/>
                       
                    </td>
                 </tr>
                <tr style="text-align:center">
                    <td><button style="border-color:transparent">Purchased Quantity:<br/> <span style="color:green">@pur.count</span></button></td>
                    <td><button style="border-color:transparent">Date Purchased: <br /><span  style="color:indianred">@pur.purchase_time.Date.ToString("dd MMM yyyy")</span></button></td>

                </tr>
                <tr>
                    <td colspan="2" style="text-align:center">
                        @if (pur.count > 1)
                        {
                            <select name="codes" class="form-control" style="width:100%;">
                                @foreach (var code in pur.activation_code)
                                {
                                    <option value="@code">@code</option>
                                }
                            </select>
                        }
                        else
                        {
                            foreach (var code in pur.activation_code)
                            {@code}
                        }
                    </td>
                </tr>


            </table>

            </div>

        }
        </div>
</div>
    }

<script>

    function validate() {

        var a = document.forms["Form"]["search"].value;
        if (a == null || a == "") {
            alert("Please enter a search item in the search box..");
            return false;
        }
        return true; 

       
    }
</script>

ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5-master/ShoppingCart_ASP.NET_MVC5/Views/Purchase/ViewCart.cshtml
@using ShoppingCart_ASP.NET_MVC5.Models;


@{

    var sessionId = ViewData["sessionId"];


    ViewBag.Title = "Gallery";

    var customerid = ViewBag.customer;

}
<div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12" style="text-align:right;">
                <i class="glyphicon glyphicon-user"></i> @ViewBag.firstname &nbsp;&nbsp;
                <i class="glyphicon glyphicon-retweet"></i> @Html.ActionLink("Home", "Home", "Home", null, null) &nbsp;&nbsp;
                <i class="glyphicon glyphicon-eye-open"></i> @Html.ActionLink("Purchases", "Mypurchases", "Purchase", new { customer_id = @customerid }, null) &nbsp;&nbsp;
                <i class="glyphicon glyphicon-log-out"></i> @Html.ActionLink("Logout", "Logout", "Auth", new { sessionId = @sessionId }, null)

            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-2" style="text-align:left;">
                <button style="background-color:white;" class="btn btn-outline-success"><span style="color:darkred">Total Price :</span> $ <span id='subtotal' style="color:green"></span> &nbsp;&nbsp;&nbsp;<i class="glyphicon glyphicon-shopping-cart"></i></button>
            </div>

            <div class="col-sm-7" style="text-align:left;">

                <button class="btn btn-outline-success">
                    <i class="glyphicon glyphicon-check"></i> @Html.ActionLink("Checkout", "Checkout", "Purchase", null, null)
                </button>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button class="btn btn-outline-success">
                    <i class="glyphicon glyphicon-retweet"></i> @Html.ActionLink("Continue Shopping", "Home", "Home", null, null)
                </button>
            </div>

            <div class="col-sm-3" style="text-align:right;">
                <form action="/Purchase/ViewCart" method="get">
                    <button style="border-color:transparent;border-radius:30px;padding-top:5px;">
                        <span class="glyphicon glyphicon-shopping-cart">
                        </span>
                        <span class="items">
                            <p id="count" value="" class="badge">
                                @ViewBag.Count
                            </p>
                        </span>
                    </button>

                </form>

            </div>
        </div>
    </div>
</div>


<br/>
<p><span id='count'></span></p>
<div class="container-fluid" style="width:100%">
    <center>
        <div class="row display-flex">
            @{
                <table class="table table-bordered" id='cart' style="width:70%; border-color:transparent; box-shadow: 0 1px 9px 0 rgba(0, 0, 0, 0.1), 0 1px 10px 0 rgba(0, 0, 0, 0.19);border-top-left-radius:30px;border-top-right-radius:30px;">
                    @foreach (var product in ViewBag.cart)
                    {
                        <tr style="text-align:center">

                            <td colspan="2" style="border-color:transparent;">
                                <img src="~/images/@product.pro_image" style="width:20%" />
                                <span style="color:#337ab7">@product.pro_name</span>
                                <span style="color:indianred">,</span>@product.pro_desc
                            </td>
                            <td style="border-color:transparent;padding:10px;">
                                <button style="background-color:white;" class="btn btn-outline-success"><span style="color:darkred">Item Price :</span> $ <span id='subtotal' style="color:green"></span> &nbsp;&nbsp;&nbsp;</button>
                            </td>
                            <td style="border-color:transparent;text-align:left;">@product.pro_price &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                            <td style="display: none">@product.pro_id</td>
                        </tr>
                        <tr>
                            <td style="border-top-color:transparent;border-right-color:transparent;text-align:right;width:80%">Quantity:</td>
                            <td style="border-top-color:transparent;border-right-color:transparent;text-align:right;width:20%">
                            <input type="number" style="width:padding:10px;border:2px solid darkgray;font-size:15px;" oninput="sumprice()" value=@product.count /></td>

                        </tr>
                    }
                </table>

            }
        </div>
    </center>
    </div>

        <script>
            window.onload = function () {
                sumprice();
            }
        </script>

        <script type="text/javascript">
            function sumprice() {
                var table, rows, price, i, qty, proid, subtotal, count;
                subtotal = 0;
                count = 0;
                table = document.getElementById("cart");
                rows = table.getElementsByTagName("tr");
                for (i = 0; i < rows.length / 2; i++) {
                    price = parseInt(rows[i * 2].getElementsByTagName("td")[2].innerText);
                    qty = parseInt(rows[i * 2 + 1].getElementsByTagName("input")[0].value);
                    proid = rows[i * 2].getElementsByTagName("td")[3].innerText;
                    

                    if (qty <= 0) {
                        rows[i * 2 + 1].getElementsByTagName("input")[0].value = 0;
                        qty = parseInt(rows[i * 2 + 1].getElementsByTagName("input")[0].value);
                    }
                    if (qty == 0) {
                        rows[i * 2].style.display = "none";
                        rows[i * 2 + 1].style.display = "none";
                    }
                    changeCookie(proid, qty);
                    subtotal = subtotal + price * qty;
                    count = count + qty;
                }
                document.getElementById('subtotal').innerHTML = subtotal;
                document.getElementById('count').innerHTML = count || 0;
                document.cookie = "Count=" + count + "; Path=/";
            }

            function changeCookie(pro_id, qty) {
                document.cookie = pro_id + "=" + qty + "; Path=/";
            }


        </script>